### ISSUE TITLE
Mark as 1.19.1 compatible

### ISSUE THREAD

**Issue by Sunconure11** [ArtixAllMighty/HangMan#12]
Just what the title says.

**Comment by AbsolemJackdaw** [comment]
Is it compatible with 1.19.1 ? 
I havent tested that yet.

**Comment by Sunconure11** [comment]
It does not run, since it is not marked in the code as being supported

**Comment by AbsolemJackdaw** [comment]
Then it needs to be updated, not marked. Im on a holiday. I can mark files for 1.19.1 on CF but i cant update them

**Comment by AbsolemJackdaw** [comment]
mod has been updates since, closing issue.
