### ISSUE TITLE
would like to add functionality

### ISSUE THREAD

**Issue by Kaitouhan** [ArtixAllMighty/HangMan#14]
I would like to be able to add the ability for LeftHanging to interact with NPCs

**Comment by Kaitouhan** [comment]
For example, it can interact with NPCs in taterzens.
like this
![QQ截图20220910133710](https://user-images.githubusercontent.com/46903169/189470924-5876fb5f-f434-4e96-a53d-75cb06f954ba.png)

**Comment by AbsolemJackdaw** [comment]
I believe this is already possible

![image](https://user-images.githubusercontent.com/3628535/192577161-468e0383-e8c8-458c-a7b5-3a210c61c940.png)  
![image](https://user-images.githubusercontent.com/3628535/192577196-552296ae-7a91-41cb-bc05-a60e749b2ee2.png)

**Comment by AbsolemJackdaw** [comment]
I just tried downloading the mod to add to my dev environment, but the project doesnt allow downloads from third parties, so I can't add compatibility, even if I wanted too. 

Closing issue as Resolved In Limbo
