### ISSUE TITLE
Possible mixin error with Malum

### ISSUE THREAD

**Issue by Sunconure11** [ArtixAllMighty/HangMan#17]
![malum incompat](https://user-images.githubusercontent.com/5614902/190478921-4a651416-d8ca-4d2f-983f-1c839276f257.png)

And when turning off Malum, I get this:

![bootstrap](https://user-images.githubusercontent.com/5614902/190479155-ef442878-c647-4d85-958d-0de6a130c362.png)

**Comment by AbsolemJackdaw** [comment]
Posting the latest.log or crashlog will be more helpful here

**Comment by Sunconure11** [comment]
Not Malum related. Will post a log shortly.

**Comment by Sunconure11** [comment]
https://pastebin.com/qZ9r4q53

**Comment by Sunconure11** [comment]
@AbsolemJackdaw Uh, hello? I gave a log

**Comment by AbsolemJackdaw** [comment]
I was not able to look into it yet... Please be patient
