### ISSUE TITLE
[Quilt/Fabric] Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [ArtixAllMighty/HangMan#18]
**MC** 1.19.2
**QSL** 4.0.0-beta13
**Left Hanging** 4.3.1.0

The newly released version crashes on startup. The logs I provided are from testing on Quilt, but Fabric version also doesn't work (with neither Fabric nor Quilt modloader). The previous version worked fine on both.

The fact that the uploaded file has a "-dev" in its name makes me think you simply uploaded the wrong file.

Logs: https://gist.github.com/Footage2-Amply-Pounce/c1c1aee130f94cbbd33642f0b8bfa099

**Comment by AbsolemJackdaw** [comment]
god damnit
auto upload fucked up
thanks
ill uplaod a new version asap

**Comment by AbsolemJackdaw** [comment]
https://www.curseforge.com/minecraft/mc-mods/left-hanging/files/4011492

this should work
