### ISSUE TITLE
Nooses become unusable after the entity that first used it dies

### ISSUE THREAD

**Issue by uSkizzik** [ArtixAllMighty/HangMan#2]
**Steps to reproduce:**
1. Place a noose
2. Hang an entity and let it die
3. Try right-clicking or hanging another entity

**Expected result:**
You would be able to hang yourself or the other entity

**Observed result:**
Nothing happens. Nothing at all.

**Comment by ArtixAllMighty** [comment]
fixed in 7cb6d53b1ea6ac4d0b5bdfaae7d436a6d2f296e1
