### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by benio1394** [ArtixAllMighty/HangMan#23]
1.20.1 fabric version

https://pastebin.com/QVU9xxab

**Comment by AbsolemJackdaw** [comment]
Have you got any details on the fabric version and loader ?
nevermind, i found them in the crash report. they're the same as what the mod was made with.

i'm continuing to look

**Comment by AbsolemJackdaw** [comment]
Thanks for the report! 
Looks like I uploaded the wrong modfile. It's a dev file,  which it shouldn't be. 
Your swift report has helped a lot and was very helpful! 

A new fabric file ahs been uploaded and it currently under review. it should be done in about ten minutes. 

Kind regards,
Absolem
