### ISSUE TITLE
unable to load up mod. crashes on boot

### ISSUE THREAD

**Issue by TheRanker** [ArtixAllMighty/HangMan#7]
https://pastebin.ubuntu.com/p/DGtrgDrhsZ/

using fabric 1.18.2
0.13.13
fabric-api-0.48.0+1.18.2.jar

**Comment by Alec153** [comment]
Same here with same versions. Are there any dependencies you didn't mention? 
[crash-2022-03-18_14.53.44-server.txt](https://github.com/ArtixAllMighty/HangMan/files/8307306/crash-2022-03-18_14.53.44-server.txt)

**Comment by AbsolemJackdaw** [comment]
no, the mixin json got messed up with a last minute update push

i got a fix ready but i'm currently sick and doing a couple hospital trips. i'll see if i can push a quick fix soon

**Comment by Alec153** [comment]
Appreciated, absolutely no rush.

**Comment by AbsolemJackdaw** [comment]
the path to the main mod file can be editied by the end user , if a quick fix is needed. 
It has moved to the hangmanfolder, so you ought to change subaraki.mod.whatever to subaraki.hangman.mod
same for the other reference in there

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/0H3dzpzuOy

**Comment by AbsolemJackdaw** [comment]
3bf035d9aeaf5b42c185ab91ea5f0f1ebb8317aa
fixed
new version released
