### ISSUE TITLE
[Forge] Crash when leaving Nether

### ISSUE THREAD

**Issue by Freshah** [ArtixAllMighty/HangMan#8]
Hi!  Love the mod and and really excited to build a dark fantasy castle with it!

I was testing the mod, hanging some Brutes in a Bastion Remnant, and travelled in and out of my Portal a few times.  Usually I'm better at reproducing bugs but this one seems random.

Log below
https://pastebin.com/4R2gpZwb

**Comment by AbsolemJackdaw** [comment]
i'm currently taking a look at it, but i'm a bit stumped. update soon.

**Comment by AbsolemJackdaw** [comment]
going into nether, hanging entity, saving and leaving world will cause a world lock.

doing this will fek your save (removing nooses will not prevent world lock)

**Comment by AbsolemJackdaw** [comment]
exiting nether will cause concurrent modification exception

**Comment by AbsolemJackdaw** [comment]
issue related to chunks and tickets regarding entities starting to mount

**Comment by AbsolemJackdaw** [comment]
error can also occur hanging up a noose in the overworld

tested :
go to nether
hang in nether x1
go to overworld
hang 2
go to nether
remove 1
go to overworld
go back
hang 1 in nether
overworld
remove 2
go nether
add 1 to hang
go overworld
place noose

**Comment by Freshah** [comment]
I wish I could do more to help you friend,

**Comment by AbsolemJackdaw** [comment]
both save lock and nether exit crash fixed.
can't pinpoint it exactly to reference the commits ... but it may have had to do something with rider positioning

new version has been released

**Comment by Freshah** [comment]
Congrats!  I'll be able to test in a few hours
